version: '3.8'

services: 
  postgresql:
    container_name: postgresql
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=PersonalEconomy
    volumes:
      - db-data:/var/lib/postgresql/data

  mongodb:
      image: 'mongo'
      env_file: ./.env
      volumes:
        - ./mongo-data:/data/db
      ports:
        - "27018:27017"
      environment: 
        MONGO_DB_USER: $MONGO_DB_USER
        MONGO_DB_PASSWORD: $MONGO_DB_USER
      logging: 
          driver: none
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - postgresql
    links:
      - postgresql
      - mongodb
    volumes: 
      - .:/app 

volumes: 
  db-config:
  db-data:
  database: