version: '3.8'

services: 
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    logging: 
      driver: none

  mongodb:
      image: 'mongo'
      env_file: ./.env
      volumes:
        - ./mongo-data:/data/db
      ports:
        - "27018:27017"
      environment: 
        MONGO_DB_USER: $MONGO_DB_USER
        MONGO_DB_PASSWORD: $MONGO_DB_USER
      logging: 
          driver: none
  app:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    links:
      - mysqldb
      - mongodb
    tty: true
    volumes: 
      - .:/app 

volumes: 
  db-config:
  db-data: